include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    unnecessary_lambdas: true