name: event_bloc_tester
description: A test package used in event_bloc
version: 0.1.1
homepage: https://github.com/VHCBlade/event_bloc_tester

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
